#a madlib game in Python
#story generated by ChatGPT with the prompt:
#create a madlib game with hip hop and esoteric references
#

#Line 1
name = input("Name: ")
adj1 = input("Adjective: ")
noun1 = input("Noun: ")
adj2 = input("Adjective: ")
verb1 = input("Verb: ")
noun2 = input("Noun: ")

#Line 2
noun3 = input("Noun: ")
adj3 = input("Adjective: ")
noun4 = input("Noun: ")
noun5 = input("Noun: ")

#Line 3
adj4 = input("Adjective: ")
pluNoun1 = input("Plural Noun: ")
pluNoun2 = input("Plural Noun: ")

#Line 4
adj5 = input("Adjective: ")
noun6 = input("Noun: ")
name2 = input("Name: ")

#Line5
noun7 = input("Noun: ")
adj6 = input("Adjective: ")

#Line 6
pluNoun3 = input("Plural Noun: ")
pluNoun4 = input("Plural Noun: ")
noun8 = input("Noun: ")

#Line 7
adj7 = input("Adjective: ")
noun9 = input("Noun: ")
pluNoun5 = input("Plural Noun: ")


madlib = f"{name} the {adj1} {noun1} was feeling {adj2} as he {verb1} down the street in his {noun2}.\
     He had just dropped his newest {noun3}, entitled The {adj3} {noun4}, and it was already making waves in the {noun5} community.\
As he walked, he couldn't help but think about the {adj4} lyrics he had written about {pluNoun1} and {pluNoun2}.\
He had even thrown in a {adj5} shoutout to his favorite {noun6}, {name2}, on the track.\
But {name} was more than just a rapper. He was also a {noun7} and a student of the {adj6} arts.\
He had spent years studying the {pluNoun3} and {pluNoun4} of ancient {noun8}, and it showed in his music.\
Suddenly, {name} was interrupted by a {adj7} {noun9} selling {pluNoun1} on the corner. \" Hey man, you want to buy a {noun4}?\" the {noun9} called out.\
{name} just chuckled and kept walking. He had bigger things to worry about, like his upcoming {noun6} at the {noun5} and preparing for his next {noun3} on the {noun5} tour. \
But no matter what, {name} always made time for his true passion: creating {adj1} {noun3} that spoke to the soul."


print(madlib)
